config/routes.rb
Rails.application.routes.draw do
  get 'data/new'
  post 'data/delete'
  post 'data/search'
  get 'data/csv'
  get 'department/edit'

  get 'daypage/show'
  post 'daypage/create'
  post 'daypage/delete'
  get 'calendar/index'
  root 'calendar#index'
  post 'department/delete'
  post 'department/create'
  
  #root 'sample#indexcd'
  #root 'simple_calendar#_calendar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
require "date"
require "csv"
   	def index
	  @users = User.all
	  @departments = Department.pluck(:key)
	  #@datas = ["機工","機電","先端","電電","情通","応化","建築","都環","デ科","未ロボ","生命","知能","情報","情ネ","経営","PM","金融"]
	  @count = []
	  @count_person = []
	  if params[:start_date].nil? then
		  @date = Date.today
	  else
		  @date = Date.strptime(params[:start_date])
	  end

	  @data = @users.where(date: @date.beginning_of_month..@date.end_of_month)  
	  @departments.each do |d|
		  @count.push(@data.where(department: d).count)
	  end
	  @departments.each do |d|
		  @count_person.push(@data.where(department: d).sum(:number))
	  end
	  @memos = @data.where.not(remarks: '').order("date DESC").limit(5)
  end
end

app/controllers/concerns/csv_exportable.rb
require 'csv'

module CsvExportable
  extend ActiveSupport::Concern

  module ClassMethods
    def to_csv(header: column_names, columns: column_names, row_sep: "\r\n", encoding: Encoding::CP932)
      records = CSV.generate(row_sep: row_sep) do |csv|
        csv << header
        all.each { |record| csv << record.attributes.values_at(*columns) }
      end
      records.encode(encoding, invalid: :replace, undef: :replace)
    end
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  
  def new
    if params[:year].present? then
      @year = params[:year]
    else
      @year = ""
    end
    if params[:depart].present? then
      @depart = params[:depart]
    else
      @depart = ""
    end
    @users = User.all
    @department = Department.pluck(:key)
    end
  

  def delete
    if params[:year].present? then
      @year = params[:year]
    else
      @year = ""
    end
    if params[:depart].present? then
      @depart = params[:depart]
    else
      @depart = ""
    end
    User.find(params[:id]).destroy
    redirect_to data_new_path(year: @year,depart:@depart)
  end

  def search
    @department = Department.pluck(:key)
    
    if params[:come][:year].present? then
      @search_date = Date.new(params[:come][:year].to_i, 4, 1)
      @finish_date = Date.new(params[:come][:year].to_i + 1, 3, 31)
      #@users = User.where('date like ? ',"%#{params[:come][:year]}%")
      @users = User.where(date: @search_date..@finish_date)
      @year = params[:come][:year]
    else
      @users = User.all
      @year = ""
    end
    if params[:come][:department].present? then
      @users = @users.where("department = ?",params[:come][:department])
      @depart = params[:come][:department]
    else
      @depart = ""
    end

    render "new"
    
  end

  def csv
    #@users = User.all
    if params[:year].present? then
      @search_date = Date.new(params[:year].to_i, 4, 1)
      @finish_date = Date.new(params[:year].to_i + 1, 3, 31)
      #@users = User.where('date like ? ',"%#{params[:come][:year]}%")
      @users = User.where(date: @search_date..@finish_date)
    else
      @users = User.all
    end
    if params[:department].present? then
      @users = @users.where("department = ?",params[:department])
    end
  end
  
end

app/controllers/daypage_controller.rb
class DaypageController < ApplicationController
  def show
	require "date"
	@date = params[:date]
	@users = User.where("date = ?",params[:date]).order(:starttime)
	@nowTime = DateTime.now
	@department = Department.pluck(:name,:key)
  end

  def create
	@user = User.new()
	@user.date = params[:come][:date]
	@user.starttime = params[:come][:starttime]
	@user.finishtime = params[:come][:finishtime]
	@user.department = params[:come][:department]
	@user.year = params[:come][:year]
	@user.sex = params[:come][:sex]
	@user.contents = params[:come][:contents]
	@user.remarks = params[:come][:remarks]
	@user.number = params[:come][:number]
	@user.save
	redirect_to daypage_show_path(date: params[:come][:date])
	#redirect_to :show(date: params[:come][:date])
  end

  def delete
	@date = params[:date]
	User.find(params[:id]).destroy
	redirect_to daypage_show_path(date: @date)
  end
	

end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
  def edit
	  @data = Department.all
  end

  def delete
	  Department.find(params[:id]).destroy
	  redirect_to department_edit_path
  end

  def create
	  @department = Department.new()
	  @department.name = params[:come][:name]
	  @department.key = params[:come][:key]
	  @department.save
	  redirect_to department_edit_path
  end
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def indexcd
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/daypage_helper.rb
module DaypageHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/views/calendar/index.html.erb
<h1>日報システム</h1>

<%=link_to "CSVダウンロード", calendar_index_path(format: "csv"), class: "btn btn-warning" %>
<%= month_calendar(attribute: :start_date, end_attribute: :end_date) do |date| %>
	<p align="right">
		<font size="+2">
		<%= link_to date.day, daypage_show_path(date: date) %></p>
	<h3 align="center">
		</font>
		<%= @users.all.where("date = ?", date).count %>件
	</h3>
<% end %>
<table border="3">
	<tr>
	<th>学科</th>
	<% @departments.each do |d| %>
		<th><%= d %></th>
	<% end %>
	</tr>
	<tr>
	<th>件数</th>
	<% @count.each do |c| %>
		<th><%= c %></th>
	<% end %>
	</tr>
	<tr>
	<th>人数</th>
	<% @count_person.each do |c| %>
		<th><%= c %></th>
	<% end %>
	</tr>
</table>
<b>
<table border="3">
	<tr>
		<th>日付</th>
		<th>学科</th>
		<th>備考欄</th>
	</tr>
	<% @memos.each do |d| %>
	<tr>
	<th><%= d.date %></th>
	<th><%= d.department %></th>
	<th><%= d.remarks %></th>
	</tr>
	<% end %>
</table>

app/views/data/new.html.erb
<h1>データ編集用ページ</h1>

<%= form_for :come, url: data_search_path do |f| %>
<table border="2">
<tr>
    <th>年度</th>
    <th>学科</th>
</tr>    
<tr>
    <th><%= f.text_area :year , :maxlength => 4,:size=>"20*10" %></th>
    <th><%= f.select(:department, @department,:include_blank => "") %></th>
    <th><p><%= f.submit "検索" %></p></th>
</tr>
	 		
<% end %>
</table>
<br>
<%=link_to "CSVダウンロード", data_csv_path(format: "csv", year: @year,department: @depart), class: "btn btn-warning"%>

<table border="3">	
    <tr>
        <th align="center">日付</th>
		<th align="center">開始時間</th>
		<th align="center">終了時間</th>
		<th align="center">学科</th>
		<th align="center">学年</th>
		<th align="center">性別</th>
		<th align="center">相談内容</th>
		<th align="center">備考</th>
		<th align="center">人数</th>
	</tr>
    <% @users.each do |user| %>
        <tr>
            <td align="center">
                <%= user.date  %>
            </td>
			<td align="center">
				<% if user.starttime.present? %>
					<%= user.starttime.strftime("%H:%M") %>
				<% end %>
			</td>
			<td align="center">
				<% if user.finishtime.present? %>
					<%= user.finishtime.strftime("%H:%M")  %>
				<% end%>
			</td>
			<td align="center"><%= user.department  %></td>
			<td align="center"><%= user.year  %></td>
			<td align="center"><%= user.sex  %></td>
			<td><%= user.contents  %></td>
			<td><%= user.remarks  %></td>
			<td align="center"><%= user.number %></td>
			<td align="center"><%= button_to "削除", data_delete_path(id: user.id)%></td>
		</tr>
	<% end %>
</table>
<br>

app/views/daypage/show.html.erb
<h1><%= @date %></h1>
<h3><%= button_to "戻る", root_path(start_date: @date), method: :get %></h3>
<table border="3">	
	<tr>
		<th align="center">開始時間</th>
		<th align="center">終了時間</th>
		<th align="center">学科</th>
		<th align="center">学年</th>
		<th align="center">性別</th>
		<th align="center">相談内容</th>
		<th align="center">備考</th>
		<th align="center">人数</th>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td align="center">
				<% if user.starttime.present? %>
					<%= user.starttime.strftime("%H:%M") %>
				<% end %>
			</td>
			<td align="center">
				<% if user.finishtime.present? %>
					<%= user.finishtime.strftime("%H:%M")  %>
				<% end%>
			</td>
			<td align="center"><%= user.department  %></td>
			<td align="center"><%= user.year  %></td>
			<td align="center"><%= user.sex  %></td>
			<td><%= user.contents  %></td>
			<td><%= user.remarks  %></td>
			<td align="center"><%= user.number %></td>
			<td align="center"><%= button_to "削除", daypage_delete_path(date:@date,id: user.id)%></td>
		</tr>
	<% end %>
</table>
<br>

<%= form_for :come, url: daypage_create_path(date: @date) do |f| %>
<table border="1">
	<caption><b>入力フォーム</b></caption>
	<%= f.hidden_field :date , :value => @date %>
	<tr>
		<th>
			<h3>開始時間</h3>
			<%= f.time_field :starttime,{min: '13:00',max: '17:59', value: @nowTime.strftime("%H:%M")}%>
		</th>
		<th>
			<h3>終了時間</h3>
			<%= f.time_field :finishtime,{min: '13:00',max: '18:00',value: @nowTime.strftime("%H:%M")} %>
		</th>
		<th>
			<h3>学科</h3>
	 		<%= f.select(:department, @department) %>
		</th>
		<th>
			<h3>学年</h3>
			<%= f.select(:year, [["1",1],["2",2],["3",3],["4",4]]) %>
		</th>
		<th>
			<h3>性別</h3>
			<%= f.select(:sex, [["男","m"],["女","f"]]) %>
		</th>
		<th>
			<h3>人数</h3>
			<%= f.select(:number, [["1",1],["2",2],["3",3],["4",4],["5",5],["6",6],["7",7]]) %>
		</th>
	</tr>
	<tr>
		<th colspan='6'>
			<h3>相談内容</h3>
			<%= f.text_area :contents, placeholder: '相談内容' , :size=>"60*100" %>
		</th>
	</tr>
	<tr>
		<th colspan='6'>
			<h3>備考</h3>
			<%= f.text_area :remarks, placeholder: '備考' , :size=>"60*50" %>
		</th>
	</tr>
	<tr>
		<th colspan='6' >
			<p><%= f.submit "保存" %></p>
		</th>
	</tr>
</table>
<% end %>

app/views/department/edit.html.erb
<h1>学科編集画面</h1>
<table border="3">
	<tr>
		<th align="center">学科</th>
		<th align="center">キー</th>
	</tr>
	<% @data.each do |d| %>
		<tr>
			<td align="center"><%= d.name %></td>
			<td align="center"><%= d.key %></td>
			<td align="center"><%= button_to "削除" ,department_delete_path(id: d.id) %></td>
		</tr>
	<% end %>
</table>
<h2>追加フォーム</h2>
<%= form_for :come, url: department_create_path do |f| %>
	<h3>学科名</h3>
	<%= f.text_area :name , :size=>"60*20" %>
	<h3>キー</h3>
	<%= f.text_area :key , :size=>"60*20" %>
	<p><%= f.submit "追加" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>citsaOffice</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag '//www.google.com/jsapi', 'application', 'data-turbolinks-track': 'reload' %>  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sample/indexcd.html.erb
<h1>Sample#indexcd</h1>
<p>Find me in app/views/sample/indexcd.html.erb</p>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <h2 class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></h2>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <h2 class="calendar-heading" align="center">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>